site_name: StampCast
site_url: https://stamp.archsted.com
site_author: '会長 / Archsted (@etude_kaicho)'
theme:
  name: 'material'
extra_css:
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
extra:
  font:
    text: "Noto Sans JP"
    code: "Consolas"
pages:
  - ホーム: index.md
  - はじめに: read1st.md
